apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  labels:
    type: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
      - name: weather-service
        image: cloud-native-weather-golang
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.25"
          limits:
            memory: "128Mi"
            cpu: "0.5"
        livenessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 5
          httpGet:
            port: http
            path: "/"
        readinessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 3
          httpGet:
            port: http
            path: "/"
        ports:
          - name: http
            containerPort: 8080
        envFrom:
          - configMapRef:
              name: database-configmap
          - secretRef:
              name: database-secrets